apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  # property-like keys; each key maps to a simple value


  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS webappdb;
    CREATE DATABASE webappdb; 
